### PR TITLE
Add support for Rails 5

### PR DESCRIPTION
**Pull request by eitoball**

### CODE REVIEW

**Comment by supermomonga** [comment]
@r7kamura Can I expect your reaction for this Pull Request?

**Comment by r7kamura** [comment]
Sorry, I apologize for missing this PR until mentioned. I agree with the change of lib/weak_parameters/hash_validator.rb, but I disagree to introduce appraisal gem at this timing. If it was not included, I would just want to merge this PR.

**Comment by eitoball** [comment]
Thank you for checking out this PR.

> but I disagree to introduce appraisal gem at this timing. I

How would you want me do on this PR, just remove appraisal gem and `Appraise`, and leave `gemfiles/*` or remove everything related to appraisal gem? If removing everything, which version of rails should weak_parameters depend?

**Comment by r7kamura** [comment]
It's desirable to leave only 25027b1f3665df3bcd6db84b31d4fe7944f6c47f. Also I think it's ok to end of support of Rails 4 because Rails 5 has been already released.

**Comment by r7kamura** [comment]
For now just merged only https://github.com/r7kamura/weak_parameters/commit/25027b1f3665df3bcd6db84b31d4fe7944f6c47f and released v0.4.0

**Pull request closed without merging**
