### PR TITLE
Add support allow blank option

### PR DESCRIPTION
**Pull request by kenchan0130**
In the most part, Rails has empty value if input value is empty with the form.
So, user must be conscious of blank value within the block.

I add support `allow_blank` option.

thank you

### CODE REVIEW

**Comment by r7kamura** [comment]
Looks good for me, but I'm not using this library in these years, so I would like to hear other contributors' or users' thoughts... does anyone have any comments on this change?

**Comment by taiki45** [comment]
I'm not clear for the use case for this option. Can you explain more detail? I'm thinking the difference between this option and "without `required` option".

**Comment by kenchan0130** [comment]
For example, when the request parameters are

```ruby
params[:message]
# => "My name is John Smith."
params[:phone_number]
# => ""
```

and, defined validator as follows

```ruby
validates :create do
  string :name, required: true do |vaue|
    value =~ /\A[a-zA-Z0-9]+\z/
  end
  string :phone_number do |value|
    TelephoneNumber.parse(value, :jp).valid?
  end
end
```

where `TelephoneNumber.parse` is a method for determining whether it is a telephone number.

In this case, raise `WeakParameters::ValidationError` because `params[:phone_number]` is empty string.
Since `phone_number` is optional, someone might think that could not reach the block.

Of course, we can do as follows

```ruby
validates :create do
  string :name, required: true do |vaue|
    value =~ /\A[a-zA-Z0-9]+\z/
  end
  string :phone_number do |value|
    value.blank? || TelephoneNumber.parse(value, :jp).valid?
  end
end
```

but I think that this option is more intuitive.

**Comment by taiki45** [comment]
Thank you for sharing the use case. Now I can understand it is what you said "In the most part, Rails has empty value if input value is empty with the form.".

>but I think that this option is more intuitive.

In my opinion, still I don't understand the benefit of adding new option for that. We can write "allow blank string" with existing feature and it's not complicated. What is the benefit of `allow_blank` option compared with "writing `value.blank?` in block"?

**Comment by r7kamura** [comment]
I'd like to know more real example usage about the `:allow_blank` option too 👀

**Comment by kenchan0130** [comment]
I don't have usage anymore.

> What is the benefit of allow_blank option compared with "writing value.blank? in block"?

If you say this, I think that it will mean that not only `allow_blank`, but also `required` option is not needed because we can write like this:

```ruby
validates :create do
  string :name, required: true do |vaue|
    value =~ /\A[a-zA-Z0-9]+\z/
  end
end

validates :create do
  string :name do |vaue|
    value.present? && value =~ /\A[a-zA-Z0-9]+\z/
  end
end
```

So, I think that this option is more intuitive.

**Comment by taiki45** [comment]
>If you say this, I think that it will mean that not only allow_blank, but also required option is not needed

Offering `required` option has an advantage that we can use this information in API document. But in your use case, it seems you won't use the option for API document. Besides, in my humble opinion, Web API which shows "it accepts blank string" seems strange for me. So currently, I think having `required` option bring us one benefit and having `allow_blank` option does not.

Saying "intuitive", I think "`value.present?` or `value.blank?` in block" is more intuitive and simple for me.

**Comment by kenchan0130** [comment]
I certainly thought it was as an API document.
I close this PR because I think that this library should be thin. 

Thank you for your feedback.

**Comment by taiki45** [comment]
Thank you for sending the PR!

In your use case, this option is used for web form input value. Does really the web form send to their input values to Web APIs which needs API documents?  I'm not clear about that use case.

**Comment by kenchan0130** [comment]
When the web client is hybrid which has rendering in server with react.js, vue.js or etc, I think that Web API could be helpful for it.

**Comment by taiki45** [comment]
Do you use exactly same URL (and Rails Controller) for Web form input and XHR? I usually split into different endpoints for those use case, but if you do so, please feel free to re-open this and I'll get this merged.

**Pull request closed without merging**
