### PR TITLE
Support rails-api

### PR DESCRIPTION
**Pull request by kenchan0130**
The controller is able to extend`ActionController::Base` or `ActionController::API` in Rails 5.

### CODE REVIEW

**Comment by kenchan0130** [comment]
I'm worried about how to write some tests for this.

**Comment by r7kamura** [comment]
@kenchan0130 Thanks for your PR, it looks good. I think you can test it by adding a controller that inherits ActionController::API into our test application.

**Comment by kenchan0130** [comment]
@r7kamura Okey, I see. I'll try it.

**Comment by kenchan0130** [comment]
@r7kamura 

I tried writing some tests.
How is this?

**Comment by kenchan0130** [comment]
@r7kamura ping

**Comment by r7kamura** [comment]
Sorry for my late, the test cases looks enough 🙏 
Thanks for your contribution!

**Pull request merged**
