### PR TITLE
Add support to specify a option to the list validator

### PR DESCRIPTION
**Pull request by laboone**
The required option of list validator does not work now.
This PR fix it.
I would be really glad if you could review and merge this:pray:

### CODE REVIEW

**Comment by r7kamura** [comment]
@mzp Do you have any thoughts?

**Comment by r7kamura** [comment]
> The required option of list validator does not work now.

😨

**Comment by r7kamura** [comment]
Merged and just released v0.4.2 ✨ 💎 ✨ 
Thanks @laboone!

**Comment by laboone** [comment]
Thank you for merging:sparkles::sparkles::sparkles:

**Pull request merged**
